name: My cool action
description: Just to showcase GitHub Actions typing
typingSpec: krzema12/github-actions-typing@v0.1
inputs:
  verbose:
    description: 'Set to true to display debug information helpful when troubleshooting issues with this action.'
    required: false
    default: 'false'
    type: boolean
  log-level:
    description: 'Specify the level of details for logging.'
    required: true
  permissions:
    description: 'Who should have access.'
    type: inttteger
runs:
  using: 'node16'
  image: 'dist/main.js'
