name: "Test workflow"
on:
  workflow_dispatch: ""
jobs:
  "test_job":
    runsOn: "ubuntu-latest"
    steps:
    - !<it.krzeminski.githubactions.yaml.YamlRunStep>
      name: "Hello world!"
      run: "echo 'hello!'"
