name: "Test workflow"
on:
  push: {}
jobs:
  "test_job":
    runs-on: "ubuntu-latest"
    steps:
    - 
      uses: "actions/checkout@v2"
      with:
        
        fetch-depth: 1
    - 
      name: "Hello world!"
      run: "echo 'hello!'"
    needs: []
    strategy: {}
