name: "Test workflow"
on:
  push: {}
jobs:
  "check_yaml_consistency":
    runs-on: "ubuntu-latest"
    steps:
    - 
      name: "Install Kotlin"
      run: "sudo snap install --classic kotlin"
    - 
      name: "Consistency check"
      run: "diff -u '.github/workflows/test_workflow.yaml' <('.github/workflows/test_workflow.main.kts')"
    needs: []
    strategy: {}
  "test_job":
    runs-on: "ubuntu-latest"
    steps:
    - 
      uses: "actions/checkout@v2"
      with:
        
        fetch-depth: 1
    - 
      name: "Hello world!"
      run: "echo 'hello!'"
    needs: []
    strategy: {}
